name: Phase 7 - Hub Public ALB

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "terraform/phase7-hub/**"
      - "terraform/modules/phase7-public-alb/**"
      - ".github/workflows/phase7-hub.yaml"

permissions:
  id-token: write
  contents: read

jobs:

  phase7-hub:
    name: Phase 7 - Hub Public ALB
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.HUB_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/phase7-hub
        run: terraform init

      - name: Terraform Format
        working-directory: terraform/phase7-hub
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: terraform/phase7-hub
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/phase7-hub
        run: |
          terraform plan \
            -out=tfplan \
            -input=false \
            -var="aws_region=${{ vars.AWS_REGION }}" \
            -var="hub_vpc_id=${{ vars.HUB_VPC_ID }}" \
            -var='hub_public_subnet_ids=["${{ vars.HUB_PUBLIC_SUBNET_1 }}","${{ vars.HUB_PUBLIC_SUBNET_2 }}"]' \
            -var='hub_private_subnet_ids=["${{ vars.HUB_PRIVATE_SUBNET_1 }}","${{ vars.HUB_PRIVATE_SUBNET_2 }}"]' \
            -var="spoke_endpoint_service_name=${{ secrets.SPOKE_ENDPOINT_SERVICE_NAME }}"

      - name: Terraform Apply
        working-directory: terraform/phase7-hub
        run: |
          terraform apply \
            -input=false \
            -auto-approve \
            tfplan

      - name: Show ALB URL
        working-directory: terraform/phase7-hub
        run: |
          echo "Public ALB:"
          terraform output alb_dns_name  